# Generated by Django 2.2.6 on 2020-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/search?q=placeholder+food&rlz=1C1GCEA_enIN867IN867&sxsrf=ALeKk009psGBLYkMUu3cbwUqUcdIrByu6w:1585165738608&tbm=isch&source=iu&ictx=1&fir=Q8g5eFdEpaSJUM%253A%252CHmujbtPCZHgLvM%252C_&vet=1&usg=AI4_-kQF8bLafvWR0LrXBgkcHnJRbBcTRg&sa=X&ved=2ahUKEwjk2onGsrboAhVN73MBHYwgD3gQ9QEwA3oECAoQGw#imgrc=Q8g5eFdEpaSJUM:', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
