# Generated by Django 2.2.6 on 2020-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=200)),
                ('original_publication_year', models.IntegerField()),
                ('original_title', models.CharField(max_length=200)),
                ('language_code', models.CharField(max_length=200)),
                ('average_rating', models.FloatField()),
                ('image_url', models.CharField(default='https://ibf.org/site_assets/img/placeholder-book-cover-default.png', max_length=500)),
            ],
        ),
    ]
